#for every new shop-service change this field
server:
  port: 28880

topic:
  delivery:
    name: t.delivery
  delivery-result:
    name: t.delivery-result
  order:
    name: t.order
  catalogue:
    name: t.catalogue
  amount:
    name: t.amount
  payment:
    name: t.payment

#for every new shop-service change this field
shop:
  service-name: shop1

spring:
  kafka:
    #bootstrap-servers: "kafka:9092"
    bootstrap-servers: "localhost:9093"
    jaas:
      enabled: true
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: earliest
      #for every new shop-service change this field
      group-id: "shop1"

  datasource:
    url: jdbc:postgresql://localhost:5434/postgresShop1DB
    #url: jdbc:postgresql://postgres-container-shop1:5434/postgresShop1DB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://127.0.0.1:8080/auth
  #auth-server-url: http://keycloak:8080/auth
  realm: "MCS"
  #for every new shop-service change this field
  resource: "shop1-client"
  bearer-only: true
  ssl-required: external
  #for every new shop-service change this field
  credentials:
    secret: super_secret_password_for_shop1_service
  confidential-port: 0

logging:
  level:
    org:
      springframework:
        security: off